.F.............
======================================================================
FAIL: test_game_to_review (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "app/tests.py", line 20, in test_game_to_review
    self.assertTrue(reviews.game == None)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 15 tests in 0.044s

FAILED (failures=1)
